consumer_key: G34qbDJO9uspOQFHrOVQ
consumer_secret: HI5rydWJkNoX8xFSaHjwPYYtTLYH5DBdvzk27bFp8
#oauth_confirm_url: http://twitter2mixi.cyberwave.jp:4567/auth
oauth_confirm_url: http://localhost:4567/auth
