##
## twitter2mixi sample yaml file
##
#
# please rewrite your enviroment.
#

env: test

consumer_key: replace_your_consumer_token
consumer_secret: replace_your_consumer_secret_token

oauth_confirm_url: http://yourdomain.com/auth
# oauth_confirm_url: http://localhost:4567/auth


# this is test account for rspec
mixiemail: replace_your_mixi_email
mixipassword: replace_your_mixi_password
twitter_token: replace_your_twitter_token
twitter_secret: replace_your_twitter_secret

bitly_api_key: replace_your_bit.ly_api_key
bitly_login_id: replace_your_bit.ly_login_id
